-- V1 baseline: schema real extraido de la DB (12 tablas). Los entornos con
-- schema existente usan baseline-on-migrate y no ejecutan este archivo.
-- Los entornos vacios (dev nuevo, staging) lo ejecutan completo.

CREATE TABLE "bugs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "category" VARCHAR(255),
    "date" DATE,
    "description" VARCHAR(1000),
    "fixed" BOOLEAN NOT NULL,
    "fixed_date" DATE,
    CONSTRAINT "bugs_pkey" PRIMARY KEY (id)
);

CREATE TABLE "categorias" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" VARCHAR(255),
    CONSTRAINT "categorias_pkey" PRIMARY KEY (id)
);

CREATE TABLE "chatbot" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "answer" VARCHAR(1000),
    CONSTRAINT "chatbot_pkey" PRIMARY KEY (id)
);

CREATE TABLE "chatbot_questions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "categoria" VARCHAR(255),
    "question" VARCHAR(400),
    "id_answer" BIGINT,
    CONSTRAINT "chatbot_questions_pkey" PRIMARY KEY (id),
    CONSTRAINT "fk4g31da9xvmy7s66e88swungwi" FOREIGN KEY (id_answer) REFERENCES chatbot(id)
);

CREATE TABLE "microemprendimientos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "activo" BOOLEAN NOT NULL,
    "ciudad" VARCHAR(255),
    "descripcion" VARCHAR(300),
    "enviado_por_mail" BOOLEAN,
    "fecha_creacion" DATE,
    "mas_informacion" VARCHAR(300),
    "nombre" VARCHAR(255),
    "pais" VARCHAR(255),
    "provincia" VARCHAR(255),
    "subcategoria" VARCHAR(255),
    "id_categoria" BIGINT,
    CONSTRAINT "fk2s9ucw3bp1xjo9f63gk88kxaw" FOREIGN KEY (id_categoria) REFERENCES categorias(id),
    CONSTRAINT "microemprendimientos_pkey" PRIMARY KEY (id)
);

CREATE TABLE "contacto" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fecha_creacion" DATE,
    "email" VARCHAR(255),
    "apellido_nombre" VARCHAR(255),
    "mensaje" VARCHAR(300),
    "telefono" VARCHAR(255),
    "gestionado" BOOLEAN,
    "id_micro" BIGINT,
    CONSTRAINT "contacto_pkey" PRIMARY KEY (id),
    CONSTRAINT "fk6xjx5p7c690bo8t58ka8uhorh" FOREIGN KEY (id_micro) REFERENCES microemprendimientos(id)
);

CREATE TABLE "pais" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" VARCHAR(255),
    CONSTRAINT "pais_pkey" PRIMARY KEY (id)
);

CREATE TABLE "provincia" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombre" VARCHAR(255),
    "id_pais" BIGINT,
    CONSTRAINT "fkp37jnxd9htn7o8v195jm4uvre" FOREIGN KEY (id_pais) REFERENCES pais(id),
    CONSTRAINT "provincia_pkey" PRIMARY KEY (id)
);

CREATE TABLE "publicaciones" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "active" BOOLEAN NOT NULL,
    "fecha_creacion" DATE,
    "description" VARCHAR(2000),
    "title" VARCHAR(255),
    CONSTRAINT "publicaciones_pkey" PRIMARY KEY (id)
);

CREATE TABLE "publicaciones_estadisticas" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fecha_visualizacion" DATE,
    "id_publicacion" BIGINT,
    CONSTRAINT "publicaciones_estadisticas_pkey" PRIMARY KEY (id),
    CONSTRAINT "fk48nyeo567a6mh0po3lu04uhof" FOREIGN KEY (id_publicacion) REFERENCES publicaciones(id)
);

CREATE TABLE "usuarios" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "activo" BOOLEAN NOT NULL,
    "apellido" VARCHAR(255),
    "email" VARCHAR(255),
    "imagen" VARCHAR(600),
    "nombre" VARCHAR(255),
    "rol" VARCHAR(255),
    "suscribed" BOOLEAN,
    "telefono" VARCHAR(255),
    CONSTRAINT "usuarios_pkey" PRIMARY KEY (id)
);

CREATE TABLE "imagenes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "url" VARCHAR(255),
    "id_publicacion" BIGINT,
    "id_micro" BIGINT,
    "fecha_subida" TIMESTAMP,
    "public_id" VARCHAR(255),
    "id_uploaded_by" BIGINT,
    CONSTRAINT "fkb7b5ka5ew9lyh5okldnmq6lwx" FOREIGN KEY (id_publicacion) REFERENCES publicaciones(id),
    CONSTRAINT "fke3wk22ne7ass5ayg1ldrh70bf" FOREIGN KEY (id_uploaded_by) REFERENCES usuarios(id),
    CONSTRAINT "fksekvs4hcteofvaln6lwmagtx4" FOREIGN KEY (id_micro) REFERENCES microemprendimientos(id),
    CONSTRAINT "imagenes_pkey" PRIMARY KEY (id),
    CONSTRAINT "uktan72v3xiado790egx4g48b3x" UNIQUE (public_id)
);

CREATE TABLE "refresh_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "user_email" VARCHAR(255) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "revoked" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY (id),
    CONSTRAINT "uk_refresh_tokens_hash" UNIQUE (token_hash)
);
