-- V2: tabla de refresh tokens (entidad nueva posterior al baseline).
-- En schemas ya existentes (baseline) se crea aquí; en schemas nuevos la crea V1.
-- IF NOT EXISTS la hace idempotente en ambos casos.

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "user_email" VARCHAR(255) NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "revoked" BOOLEAN NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY (id),
    CONSTRAINT "uk_refresh_tokens_hash" UNIQUE (token_hash)
);
